
General:
    client_ip: "127.0.0.1"
    server_ip: "0.0.0.0"
    port: 8080
    number_rounds: 1

Dataset:
    dataset_path: datasets/HDFS
    seed_number: 10
    train_per: 0.01
    dist_method: Uniform
    dist_plot_path: "distribution_plot.png"

Deeplog:
    device: 'cpu'
    validation_rate: 0.1
    window_size: 10
    input_size: 1
    hidden_size: 64
    num_layers: 2
    num_classes: 32
    batch_size: 2048
    accumulation_step: 1
    lr: 0.001
    max_epoch: 10
    lr_step: (300, 350)
    lr_decay_ratio: 0.1
    num_candidates: 9

